### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kamada-maki** [kamada-maki/furima-32507#11]
-本番環境URL
https://furima-32507.herokuapp.com/

-Basic認証のIDとパスワード
ID: furima-32507
Password:32507

-出品者用のメールアドレスとパスワード
Email: test@test
Password:test123

-購入者用のメールアドレスとパスワード
Email: test.test@gmail.com
Password:test123

-購入用カードの番号・期限・セキュリティコード
番号　4242424242424242
期限　12月／24年
セキュリティコード　123

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・提出いただいたbasic認証のIDとパスワードでフリマアプリのページを開くことができませんでした。こちら正しいIDとパスワードであるかどうか確認の上、再度送っていただいてもよろしいでしょうか？

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kamada-maki** [comment]
issuenに記載をしたIDが間違えており、修正しております。
ご確認お願いいたします。（フォーム再提出済です）

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・パスワードは英数字混合で登録できるようにしましょう。現在は数字のみでも新規登録ができてしまいますので、英数字混合以外のパスワードが入力された際には、エラーハンドリングができるようにい修正をお願いします。

・送っていただいた以下の購入者用のアドレスにてログインすることができませんでしたので、今一度ご確認をお願いします。
-購入者用のメールアドレスとパスワード
Email: test.test@gmail.coom
Password:test123

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kamada-maki** [comment]
パスワードが半角英数字混合でないとエラーハンドリングができるよう修正しました。
購入用のアドレスとパスワードも修正しています。
ご確認お願いいたします。（フォーム再提出済）

**Comment by eeee-0000** [comment]
ご提出ありがとうございます！
前回の修正箇所1点は修正完了しております。修正対応ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・依然として、送っていただいた以下の購入者用のアドレスにてログインすることができませんでした。
今一度ご確認をお願いします。

-購入者用のメールアドレスとパスワード
Email: test.test@gmail.coom
Password:test123

![image](https://user-images.githubusercontent.com/62004107/101441766-2aef4e00-395d-11eb-85d0-7ddf6c9762d5.png)


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kamada-maki** [comment]
前回の修正、提出時にアドレスが間違えていたため修正しています。
送ってくださった画像ではまだ前回のままのアドレスかと思われます。
念の為以下にも記載しておきます。
お手数おかけしますがよろしくお願いいたします。

-購入者用のメールアドレスとパスワード
Email: test.test@gmail.com
Password:test123

**Comment by eeee-0000** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
